### ISSUE TITLE
Not working in Edition 2021 

### ISSUE THREAD

**Issue by jerusdp** [dbrgn/tracing-test#10]
The tracing-test macro is not working in a project compiled as edition 2021.  (Currently Rust beta )

Tests are failing on `assert!(log_contains("text"));`

**Comment by threema-danilo** [comment]
Hi, can you create a small reproducer?

If I change the edition for the `tracing-test-macro-tests` subcrate to 2021 and run the tests on beta, they still pass.

**Comment by jerusdp** [comment]
Apologies for the false flag - the test was failing for good reason. 

No issue here.
