### ISSUE TITLE
how does tracing-test work with targeted spans?

### ISSUE THREAD

**Issue by mooreniemi** [dbrgn/tracing-test#2]
Hello again. 😅 

In my application I use `target`s like:

```
tracing::error!(target: "my_cool_app", "failure: {:?}", b);
```

I am finding that any logs I emit from `target`ed span appear in my logs as expected when running the application, but `logs_contain` can't see them.

So:

```
tracing::debug!("content_length: {:?}", resp.content_length()); // tests pass
tracing::error!(target: "my_cool_app", "failure: {:?}", b); // tests don't pass
```

Are `target`s supported or not? If so, what do I need to do to see them?

**Comment by mooreniemi** [comment]
I figure it is down to the `env_filter` somehow? Means the `subscriber` can't "see" anything in a `target`?

```
let env_filter = format!("{}=trace", crate_name);
let mock_writer = tracing_test::internal::MockWriter::new(&tracing_test::internal::GLOBAL_BUF);
let subscriber = tracing_test::internal::get_subscriber(mock_writer, &env_filter);
```

From https://github.com/dbrgn/tracing-test/blob/main/tracing-test-macro/src/lib.rs#L67

**Comment by dbrgn** [comment]
Sorry for late reply. In #4 there's another report of the same issue. I'll close this one since the other issue has a slightly better description, feel free to add more information there in case you found out what the reason for this behavior is.
