### ISSUE TITLE
Allow setting log capture level

### ISSUE THREAD

**Issue by benjaminran** [dbrgn/tracing-test#28]
Hi there, would you be interested in accepting a PR to allow changing the log level from the default of trace? I'm imagining cutting down the level both for log output and logs_contain().

E.g something like `#[traced_test(level = "info")]`.

I mainly want this in order to quiet the log output I get back when running traced tests.

**Comment by dbrgn** [comment]
I'm not sure if this is really needed. By default, log capturing will capture your test logs anyways, wouldn't it?

**Comment by benjaminran** [comment]
Sorry to respond slowly - on second thought I guess I don't need this that badly. Log capture does help a lot; it's just if a test ever fails and the logs are outputted then it can be a bit shocking 😅. But even then I guess it's fine to just filter out TRACE lines. Closing this....
